image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose version
  - docker-compose build
  - docker-compose up &
  - sleep 30
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar ./artifacts/aqa-shop.jar &
  - sleep 10
build_script:
  - sleep 20
  - ./gradlew test -Dselenide.headless=true -Durl=jdbc:mysql://localhost:3306/app --info