image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose version
  - docker-compose build
  - sleep 5
  - docker-compose up
  - sleep 15
  - java -jar ./artifacts/aqa-shop.jar &
  - sleep 10
build_script:
  - ./gradlew test -Dselenide.headless=true --info